/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iescomercio.data;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

/**
 *
 * @author Nocturno
 */
public class Clientes extends javax.swing.JInternalFrame {

    private  ListaClientes listaClientes;
    private int indice;
    private final VError v;

    /**
     * Creates new form Clientes
     *
     * @param listaClientes
     */
    public Clientes(ListaClientes listaClientes) {
        initComponents();
        setSize(380, 480);
        setTitle("Clientes");
        this.listaClientes = listaClientes;
        indice = 0;
        v = new VError(null, rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxEstadoCivil = new javax.swing.JComboBox();
        jCheckBoxSocio = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTelefonoFijo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonPrimero = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonBorrar = new javax.swing.JButton();
        jLabelInfoCliente = new javax.swing.JLabel();
        jTextFieldTelefonoMovil = new javax.swing.JTextField();
        jLabelInfoException = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 90, 22);
        getContentPane().add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(130, 70, 200, 26);
        getContentPane().add(jTextFieldDni);
        jTextFieldDni.setBounds(130, 100, 200, 26);

        jLabel4.setText("DNI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 90, 22);
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(130, 130, 200, 26);

        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 130, 90, 22);
        getContentPane().add(jTextFieldApellidos);
        jTextFieldApellidos.setBounds(130, 160, 200, 26);

        jLabel6.setText("Apellidos");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 90, 22);

        jLabel7.setText("Socio");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 220, 90, 22);

        jComboBoxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Soltero/a", "Casado/a" }));
        getContentPane().add(jComboBoxEstadoCivil);
        jComboBoxEstadoCivil.setBounds(130, 190, 120, 22);
        getContentPane().add(jCheckBoxSocio);
        jCheckBoxSocio.setBounds(130, 220, 21, 21);

        jLabel8.setText("Estado Civil");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 190, 90, 22);

        jLabel9.setText("Dirección");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 250, 90, 22);
        getContentPane().add(jTextFieldDireccion);
        jTextFieldDireccion.setBounds(130, 250, 200, 26);

        jLabel10.setText("Teléfono Fijo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 280, 90, 22);
        getContentPane().add(jTextFieldTelefonoFijo);
        jTextFieldTelefonoFijo.setBounds(130, 280, 120, 26);

        jLabel11.setText("Edad");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 340, 90, 22);
        getContentPane().add(jTextFieldEdad);
        jTextFieldEdad.setBounds(130, 340, 120, 26);

        jLabel12.setText("Teléfono Móvil");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 310, 90, 22);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/new_file.png"))); // NOI18N
        jButtonNuevo.setToolTipText("Nuevo");
        jButtonNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNuevo.setFocusable(false);
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonNuevo);

        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/save.png"))); // NOI18N
        jButtonGuardar.setToolTipText("Guardar");
        jButtonGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGuardar.setFocusable(false);
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonGuardar);

        jSeparator1.setSeparatorSize(new java.awt.Dimension(10, 40));
        jToolBar2.add(jSeparator1);

        jButtonPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/first.png"))); // NOI18N
        jButtonPrimero.setToolTipText("Primero");
        jButtonPrimero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPrimero.setFocusable(false);
        jButtonPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeroActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonPrimero);

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/previous.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAnterior.setFocusable(false);
        jButtonAnterior.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAnterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonAnterior);

        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/next.png"))); // NOI18N
        jButtonSiguiente.setToolTipText("Siguiente");
        jButtonSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSiguiente.setFocusable(false);
        jButtonSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonSiguiente);

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/last.png"))); // NOI18N
        jButtonUltimo.setToolTipText("Ultimo");
        jButtonUltimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonUltimo.setFocusable(false);
        jButtonUltimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUltimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonUltimo);

        jSeparator2.setSeparatorSize(new java.awt.Dimension(10, 40));
        jToolBar2.add(jSeparator2);

        jButtonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/delete.png"))); // NOI18N
        jButtonBorrar.setToolTipText("Borrar");
        jButtonBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBorrar.setFocusable(false);
        jButtonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonBorrar);

        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(0, 0, 370, 40);

        jLabelInfoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfoCliente.setForeground(new java.awt.Color(0, 0, 255));
        jLabelInfoCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelInfoCliente);
        jLabelInfoCliente.setBounds(210, 220, 120, 24);
        getContentPane().add(jTextFieldTelefonoMovil);
        jTextFieldTelefonoMovil.setBounds(130, 310, 120, 26);

        jLabelInfoException.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfoException.setForeground(new java.awt.Color(0, 0, 255));
        jLabelInfoException.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabelInfoException);
        jLabelInfoException.setBounds(30, 380, 300, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarFormulario() {
        // metodo para limpiar formulario
        jTextFieldCodigo.setText("");
        jTextFieldDni.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellidos.setText("");
        jComboBoxEstadoCivil.setSelectedIndex(-1);
        jTextFieldDireccion.setText("");
        jCheckBoxSocio.setSelected(false);
        jTextFieldTelefonoFijo.setText("");
        jTextFieldTelefonoMovil.setText("");
        jTextFieldEdad.setText("");
    }

    private void guardarDatos(Cliente c) {
        // metodo para leer datos del formulario y setearlos en un cliente que le pasamos
        try {
            c.setCodigo(jTextFieldCodigo.getText());
            c.setDni(jTextFieldDni.getText());
            c.setNombre(jTextFieldNombre.getText());
            c.setApellidos(jTextFieldApellidos.getText());
            c.setEstadoCivil(jComboBoxEstadoCivil.getSelectedIndex());
            c.setDireccion(jTextFieldDireccion.getText());
            c.setSocio(jCheckBoxSocio.isSelected());
            c.setTelefonoFijo(Integer.parseInt(jTextFieldTelefonoFijo.getText()));
            c.setTelefonoMovil(Integer.parseInt(jTextFieldTelefonoMovil.getText()));
            c.setEdad(Integer.parseInt(jTextFieldEdad.getText()));
            listaClientes.addCliente(c);
            this.limpiarFormulario();
        } catch (NumberFormatException ex) {
            v.setMensaje("Formato incorrecto", ex);
        }
    }

    private void recuperarDatos(Cliente c) {
        // metodo para escribir en el formulario los datos de un cliente que le pasamos
        jTextFieldCodigo.setText(c.getCodigo());
        jTextFieldDni.setText(c.getDni());
        jTextFieldNombre.setText(c.getNombre());
        jTextFieldApellidos.setText(c.getApellidos());
        jTextFieldDireccion.setText(c.getDireccion());
        jCheckBoxSocio.setSelected(c.isSocio());
        jTextFieldTelefonoFijo.setText(Integer.toString(c.getTelefonoFijo()));
        jTextFieldTelefonoMovil.setText(Integer.toString(c.getTelefonoMovil()));
        jTextFieldEdad.setText(Integer.toString(c.getEdad()));
        jComboBoxEstadoCivil.setSelectedIndex(c.getEstadoCivil());
    }

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // boton de guardar un cliente
        Cliente c = new Cliente();
        this.guardarDatos(c);
        //jLabelInfoCliente.setText("Cliente nº: " + indice);
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        // boton de limpieza de formulario
        this.limpiarFormulario();
        //jLabelInfoCliente.setText("Cliente nº: " + indice);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeroActionPerformed
        // boton que muestra el primer cliente
        try {
            Cliente c = listaClientes.recuperarPrimerCliente();
            this.recuperarDatos(c);
            indice = 0;
            //jLabelInfoCliente.setText("Cliente nº: " + indice);
        } catch (IndexOutOfBoundsException ex) {
            v.setMensaje("Acceso a datos incorrecto", ex);
        }
    }//GEN-LAST:event_jButtonPrimeroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // boton que muestra el cliente anterior de la coleccion en funcion a un indice
        try {
            if (indice < 1) {
                indice = 0;
            } else {
                indice--;
            }
            Cliente c = listaClientes.recuperarCliente(indice);
            this.recuperarDatos(c);
            //jLabelInfoCliente.setText("Cliente nº: " + indice);
        } catch (IndexOutOfBoundsException ex) {
            v.setMensaje("Acceso a datos incorrecto", ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        // boton que muestra el cliente siguiente de la coleccion en funcion a un indice
        try {
            if (indice >= listaClientes.recuperarLongitud() - 1) {
                indice = listaClientes.recuperarLongitud() - 1;
            } else {
                indice++;
            }
            Cliente c = listaClientes.recuperarCliente(indice);
            this.recuperarDatos(c);
            //jLabelInfoCliente.setText("Cliente nº: " + indice);
        } catch (IndexOutOfBoundsException ex) {
            v.setMensaje("Acceso a datos incorrecto", ex);
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // metodo que escribe el fichero al cerrar la ventana
        try {
            DataOutputStream dos = new DataOutputStream(new FileOutputStream("f:\\testdata\\clientes.txt"));
            // inicio bucle = 0
            // final bucle = la longitud de la coleccion
            for (int i = 0; i < listaClientes.recuperarLongitud(); i++) {
                Cliente c;
                // recupero la informacion de la coleccion en base a un indice que le paso
                c = listaClientes.recuperarCliente(i);
                // escribo el fichero bloque a bloque
                // cada bloque es un string con la informacion de cada elemento del formulario
                dos.writeUTF(c.getCodigo());
                dos.writeUTF(c.getDni());
                dos.writeUTF(c.getNombre());
                dos.writeUTF(c.getApellidos());
                dos.writeUTF(Integer.toString(c.getEstadoCivil()));
                dos.writeUTF(Boolean.toString(c.isSocio()));
                dos.writeUTF(c.getDireccion());
                dos.writeUTF(Integer.toString(c.getTelefonoFijo()));
                dos.writeUTF(Integer.toString(c.getTelefonoMovil()));
                dos.writeUTF(Integer.toString(c.getEdad()));
                // escribo un salto de linea para separar clientes en el fichero
                dos.writeUTF("\n");
            }
            dos.close();
        } catch (FileNotFoundException ex) {
            v.setMensaje("Fichero no encontrado", ex);
            //jLabelInfoException.setText("FileNotFoundException");
        } catch (IOException ex) {
            v.setMensaje("Error de entrada salida", ex);
            //jLabelInfoException.setText("IOException");
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // metodo que lee el fichero al abrir la ventana
        try {
            DataInputStream dis = new DataInputStream(new FileInputStream("f:\\testdata\\clientes.txt"));
            // mientras queden bytes por leer entro
            while (dis.available() != 0) {
                Cliente c = new Cliente();
                c.setCodigo(dis.readUTF().toString());
                c.setDni(dis.readUTF().toString());
                c.setNombre(dis.readUTF().toString());
                c.setApellidos(dis.readUTF().toString());
                c.setEstadoCivil(Integer.parseInt(dis.readUTF().toString()));
                c.setSocio(Boolean.parseBoolean(dis.readUTF().toString()));
                c.setDireccion(dis.readUTF().toString());
                c.setTelefonoFijo(Integer.parseInt(dis.readUTF().toString()));
                c.setTelefonoMovil(Integer.parseInt(dis.readUTF().toString()));
                c.setEdad(Integer.parseInt(dis.readUTF().toString()));
                // lee el salto de linea que separa clientes y no hace nada con el
                dis.readUTF();
                listaClientes.addCliente(c);
            }
            dis.close();
            // muestro el primer cliente al abrir el internal frame de clientes
            this.jButtonPrimeroActionPerformed(null);
        } catch (EOFException ex) {
            v.setMensaje("Error por fin de fichero", ex);
            //jLabelInfoException.setText("EOFException");
        } catch (FileNotFoundException ex) {
            v.setMensaje("Fichero no encontrado", ex);
            //jLabelInfoException.setText("FileNotFoundException");
        } catch (IOException ex) {
            v.setMensaje("Error de entrada salida", ex);
            //jLabelInfoException.setText("IOException");
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // boton que muestra el ultimo cliente
        try {
            Cliente c = listaClientes.recuperarUltimoCliente();
            this.recuperarDatos(c);
            indice = listaClientes.recuperarLongitud() - 1;
            //jLabelInfoCliente.setText("Cliente nº: " + indice);
        } catch (IndexOutOfBoundsException ex) {
            v.setMensaje("Acceso a datos incorrecto", ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // boton que borra un cliente en funcion de su indice
        try {
            this.listaClientes.borrarCliente(indice);
            this.limpiarFormulario();
            //jLabelInfoCliente.setText("Cliente borrado");
        } catch (IndexOutOfBoundsException ex) {
            v.setMensaje("Acceso a datos incorrecto", ex);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonPrimero;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JCheckBox jCheckBoxSocio;
    private javax.swing.JComboBox jComboBoxEstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInfoCliente;
    private javax.swing.JLabel jLabelInfoException;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefonoFijo;
    private javax.swing.JTextField jTextFieldTelefonoMovil;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
