/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iescomercio.data;

import java.io.PrintWriter;
import java.io.StringWriter;
//import javax.swing.JFrame;
//import javax.swing.JOptionPane;

/**
 *
 * @author Nocturno
 */
public class VError extends javax.swing.JDialog {

    String st;
    Exception e;

    /**
     * Creates new form VError
     * @param parent
     * @param modal
     */
    public VError(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(400, 150);
        setLocationRelativeTo(null);
        setTitle("Ventana Error");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/admiracion.png")).getImage());
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/error.png")));
        
        st = new String();
        e = new Exception();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelErrorPpal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMasInfo = new javax.swing.JTextArea();
        jToggleButtonInfo = new javax.swing.JToggleButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelErrorPpal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabelErrorPpal);
        jLabelErrorPpal.setBounds(20, 10, 280, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 10, 70, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 70);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(null);

        jButtonCerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCerrar.setText("Cerrar Ventana");
        jButtonCerrar.setFocusable(false);
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCerrar);
        jButtonCerrar.setBounds(250, 10, 130, 30);

        jTextAreaMasInfo.setEditable(false);
        jTextAreaMasInfo.setBackground(new java.awt.Color(153, 153, 255));
        jTextAreaMasInfo.setColumns(20);
        jTextAreaMasInfo.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMasInfo);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 360, 150);

        jToggleButtonInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jToggleButtonInfo.setText("Mas información");
        jToggleButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonInfoActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButtonInfo);
        jToggleButtonInfo.setBounds(20, 10, 130, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 400, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMensaje(String st, Exception e) {
        this.st = st;
        this.e = e;
        jLabelErrorPpal.setText(st);
        this.setVisible(true);
    }

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jToggleButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonInfoActionPerformed
        // TODO add your handling code here:
        if (jToggleButtonInfo.isSelected()) {
            setSize(400, 310);
            StringWriter errors = new StringWriter();
            e.printStackTrace(new PrintWriter(errors));
            jTextAreaMasInfo.setText(errors.toString());
        } else {
            setSize(400, 140);
            jTextAreaMasInfo.setText("");
        }
    }//GEN-LAST:event_jToggleButtonInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelErrorPpal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaMasInfo;
    private javax.swing.JToggleButton jToggleButtonInfo;
    // End of variables declaration//GEN-END:variables
}
