/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iescomercio.data;

/**
 *
 * @author Nocturno
 */
public class Vista extends javax.swing.JFrame {

    private Barcos barco;
    private Clientes cliente;
    private Deportivas deportiva;
    private Veleros velero;
    private Yates yate;
    private ListaClientes listaClientes;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setTitle("Gestión Amarres");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/iescomercio/img/ancla.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);
        listaClientes = new ListaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuBarcos = new javax.swing.JMenuItem();
        openMenuClientes = new javax.swing.JMenuItem();
        openMenuDeportivas = new javax.swing.JMenuItem();
        openMenuVeleros = new javax.swing.JMenuItem();
        openMenuYates = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestión Amarres");

        openMenuBarcos.setMnemonic('s');
        openMenuBarcos.setText("Barcos");
        openMenuBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMenu(evt);
            }
        });
        fileMenu.add(openMenuBarcos);

        openMenuClientes.setMnemonic('o');
        openMenuClientes.setText("Clientes");
        openMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMenu(evt);
            }
        });
        fileMenu.add(openMenuClientes);

        openMenuDeportivas.setMnemonic('a');
        openMenuDeportivas.setText("Deportivas");
        openMenuDeportivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMenu(evt);
            }
        });
        fileMenu.add(openMenuDeportivas);

        openMenuVeleros.setText("Veleros");
        openMenuVeleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMenu(evt);
            }
        });
        fileMenu.add(openMenuVeleros);

        openMenuYates.setText("Yates");
        openMenuYates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMenu(evt);
            }
        });
        fileMenu.add(openMenuYates);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void clickMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickMenu
        // TODO add your handling code here:
        barco = new Barcos();
        cliente = new Clientes(listaClientes);
        deportiva = new Deportivas();
        velero = new Veleros();
        yate = new Yates();

        desktopPane.add(barco);
        desktopPane.add(cliente);
        desktopPane.add(deportiva);
        desktopPane.add(velero);
        desktopPane.add(yate);

        if (evt.getSource() == openMenuBarcos) {
            barco.setVisible(true);
        } else if (evt.getSource() == openMenuClientes) {
            cliente.setVisible(true);
        } else if (evt.getSource() == openMenuDeportivas) {
            deportiva.setVisible(true);
        } else if (evt.getSource() == openMenuVeleros) {
            velero.setVisible(true);
        } else if (evt.getSource() == openMenuYates) {
            yate.setVisible(true);
        }
    }//GEN-LAST:event_clickMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuBarcos;
    private javax.swing.JMenuItem openMenuClientes;
    private javax.swing.JMenuItem openMenuDeportivas;
    private javax.swing.JMenuItem openMenuVeleros;
    private javax.swing.JMenuItem openMenuYates;
    // End of variables declaration//GEN-END:variables

}
